
FLAGS = -Wall -pthread -g

all: q1 q3 q4

clean:
	rm -f q1 q3 q4

q1: q1.c mythreads.h
	gcc -o q1 q1.c $(FLAGS)

q3: q3.c mythreads.h
	gcc -o q3 q3.c $(FLAGS)

q4: q4.c mythreads.h
	gcc -o q4 q4.c $(FLAGS)
