all: 5-Chapter6-lde[1] 5-Chapter6-lde[2] 

clean:
	rm -f 5-Chapter6-lde[1] 5-Chapter6-lde[1]

5-Chapter6-lde[1]: 5-Chapter6-lde[1].c
	gcc -o 5-Chapter6-lde[1] 5-Chapter6-lde[1].c -Wall

5-Chapter6-lde[2]: 5-Chapter6-lde[2].c
	gcc -o 5-Chapter6-lde[2] 5-Chapter6-lde[2].c -Wall
